# Generated by Django 4.2.23 on 2025-08-09 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Event Name")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TRAINING", "Training"),
                            ("EXERCISE", "Military Exercise"),
                            ("HOLIDAY", "Holiday"),
                            ("MAINTENANCE", "Equipment Maintenance"),
                            ("INSPECTION", "Inspection"),
                            ("CEREMONY", "Ceremony"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "min_required_soldiers_per_day",
                    models.IntegerField(
                        default=10, verbose_name="Min Required Soldiers Per Day"
                    ),
                ),
                (
                    "base_days_per_soldier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Base Days Per Soldier"
                    ),
                ),
                (
                    "home_days_per_soldier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Home Days Per Soldier"
                    ),
                ),
                (
                    "max_consecutive_base_days",
                    models.IntegerField(
                        default=7, verbose_name="Max Consecutive Base Days"
                    ),
                ),
                (
                    "max_consecutive_home_days",
                    models.IntegerField(
                        default=10, verbose_name="Max Consecutive Home Days"
                    ),
                ),
                (
                    "min_base_block_days",
                    models.IntegerField(default=3, verbose_name="Min Base Block Days"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Soldier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Soldier Name")),
                (
                    "soldier_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Soldier ID",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("CORPORAL", "Corporal"),
                            ("SERGEANT", "Sergeant"),
                            ("LIEUTENANT", "Lieutenant"),
                            ("CAPTAIN", "Captain"),
                            ("MAJOR", "Major"),
                            ("COLONEL", "Colonel"),
                            ("GENERAL", "General"),
                            ("CIVILIAN", "Civilian"),
                        ],
                        default="PRIVATE",
                        max_length=20,
                    ),
                ),
                (
                    "is_exceptional_output",
                    models.BooleanField(default=False, verbose_name="Leadership Role"),
                ),
                (
                    "is_weekend_only_soldier_flag",
                    models.BooleanField(default=False, verbose_name="Weekend Only"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Soldier",
                "verbose_name_plural": "Soldiers",
                "ordering": ["rank", "name"],
            },
        ),
        migrations.CreateModel(
            name="SchedulingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Schedule Name"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUCCESS", "Successfully Completed"),
                            ("FAILURE", "Failed"),
                            ("NO_SOLUTION", "No Solution Found"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("solution_details", models.TextField(blank=True, null=True)),
                ("processing_time_seconds", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduling_runs",
                        to="schedule.event",
                    ),
                ),
                (
                    "soldiers",
                    models.ManyToManyField(
                        related_name="scheduling_runs",
                        to="schedule.soldier",
                        verbose_name="Soldiers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduling Run",
                "verbose_name_plural": "Scheduling Runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SoldierConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("constraint_date", models.DateField(verbose_name="Constraint Date")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Constraint Description"
                    ),
                ),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal Leave"),
                            ("MEDICAL", "Medical"),
                            ("TRAINING", "Training/Course"),
                            ("FAMILY", "Family Event"),
                            ("OFFICIAL", "Official Duty"),
                            ("OTHER", "Other"),
                        ],
                        default="PERSONAL",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "soldier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constraints",
                        to="schedule.soldier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soldier Constraint",
                "verbose_name_plural": "Soldier Constraints",
                "ordering": ["constraint_date"],
                "unique_together": {("soldier", "constraint_date")},
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_date", models.DateField(verbose_name="Assignment Date")),
                ("is_on_base", models.BooleanField(verbose_name="Is on Base?")),
                (
                    "scheduling_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="schedule.schedulingrun",
                    ),
                ),
                (
                    "soldier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.soldier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "ordering": ["assignment_date", "soldier__name"],
                "unique_together": {("scheduling_run", "soldier", "assignment_date")},
            },
        ),
    ]
