# Generated by Django 4.2.23 on 2025-08-09 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Import Name")),
                (
                    "source_file",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Source File",
                    ),
                ),
                ("import_date", models.DateTimeField(auto_now_add=True)),
                ("total_soldiers", models.IntegerField(default=0)),
                ("successful_imports", models.IntegerField(default=0)),
                ("failed_imports", models.IntegerField(default=0)),
                ("import_settings", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Batch",
                "verbose_name_plural": "Import Batches",
                "ordering": ["-import_date"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Organization Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Organization Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Soldier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Soldier Name")),
                (
                    "soldier_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Soldier ID"
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("CORPORAL", "Corporal"),
                            ("SERGEANT", "Sergeant"),
                            ("LIEUTENANT", "Lieutenant"),
                            ("CAPTAIN", "Captain"),
                            ("MAJOR", "Major"),
                            ("COLONEL", "Colonel"),
                            ("GENERAL", "General"),
                            ("CIVILIAN", "Civilian"),
                        ],
                        default="PRIVATE",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "is_exceptional_output",
                    models.BooleanField(
                        default=False, verbose_name="Exceptional/Leadership Role"
                    ),
                ),
                (
                    "is_weekend_only_soldier_flag",
                    models.BooleanField(default=False, verbose_name="Weekend Only"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ON_LEAVE", "On Leave"),
                            ("TRANSFERRED", "Transferred"),
                            ("DISCHARGED", "Discharged"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Military Specialty",
                    ),
                ),
                (
                    "security_clearance",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "preferred_shift",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "max_consecutive_days",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Personal Max Consecutive Days",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="soldiers",
                        to="schedule.importbatch",
                        verbose_name="Import Batch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soldiers",
                        to="schedule.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soldier",
                "verbose_name_plural": "Soldiers",
                "ordering": ["organization", "unit", "rank", "name"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Unit Name")),
                ("code", models.CharField(max_length=50, verbose_name="Unit Code")),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("ORGANIZATION", "Organization"),
                            ("BATTALION", "Battalion"),
                            ("COMPANY", "Company"),
                            ("PLATOON", "Platoon"),
                            ("SQUAD", "Squad"),
                            ("TEAM", "Team"),
                            ("DEPARTMENT", "Department"),
                            ("DIVISION", "Division"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=20,
                        verbose_name="Unit Type",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "commander",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Unit Commander",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "default_min_soldiers_per_day",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Default Min Soldiers Per Day",
                    ),
                ),
                (
                    "working_days",
                    models.CharField(
                        default="1,2,3,4,5,6,7",
                        max_length=20,
                        verbose_name="Working Days (1=Mon, 7=Sun)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="schedule.organization",
                    ),
                ),
                (
                    "parent_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_units",
                        to="schedule.unit",
                        verbose_name="Parent Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "ordering": ["organization", "unit_type", "name"],
                "unique_together": {("organization", "code")},
            },
        ),
        migrations.CreateModel(
            name="SoldierConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("constraint_date", models.DateField(verbose_name="Constraint Date")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Constraint Description"
                    ),
                ),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal Leave"),
                            ("MEDICAL", "Medical"),
                            ("TRAINING", "Training/Course"),
                            ("FAMILY", "Family Event"),
                            ("OFFICIAL", "Official Duty"),
                            ("OTHER", "Other"),
                        ],
                        default="PERSONAL",
                        max_length=20,
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, verbose_name="Recurring Constraint"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "soldier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constraints",
                        to="schedule.soldier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soldier Constraint",
                "verbose_name_plural": "Soldier Constraints",
                "ordering": ["constraint_date"],
                "unique_together": {("soldier", "constraint_date")},
            },
        ),
        migrations.AddField(
            model_name="soldier",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soldiers",
                to="schedule.unit",
            ),
        ),
        migrations.CreateModel(
            name="SchedulingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_date", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "default_base_days_target",
                    models.IntegerField(verbose_name="Default Base Days Target"),
                ),
                (
                    "default_home_days_target",
                    models.IntegerField(verbose_name="Default Home Days Target"),
                ),
                (
                    "max_consecutive_base_days",
                    models.IntegerField(verbose_name="Max Consecutive Base Days"),
                ),
                (
                    "max_consecutive_home_days",
                    models.IntegerField(verbose_name="Max Consecutive Home Days"),
                ),
                (
                    "min_base_block_days",
                    models.IntegerField(verbose_name="Min Base Block Days"),
                ),
                (
                    "min_required_soldiers_per_day",
                    models.IntegerField(verbose_name="Min Required Soldiers Per Day"),
                ),
                (
                    "max_total_home_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Max Total Home Days"
                    ),
                ),
                (
                    "max_weekend_base_days_per_soldier",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Max Weekend Base Days Per Soldier",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Schedule Name"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Successfully Completed"),
                            ("FAILURE", "Failed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("NO_SOLUTION", "No Solution Found"),
                            ("CANCELLED", "Cancelled"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("solution_details", models.TextField(blank=True, null=True)),
                (
                    "algorithm_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("processing_time_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exclude_soldiers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="excluded_schedules",
                        to="schedule.soldier",
                        verbose_name="Excluded Soldiers",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduling_runs",
                        to="schedule.organization",
                    ),
                ),
                (
                    "priority_soldiers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="priority_schedules",
                        to="schedule.soldier",
                        verbose_name="Priority Soldiers",
                    ),
                ),
                (
                    "target_units",
                    models.ManyToManyField(
                        related_name="scheduling_runs",
                        to="schedule.unit",
                        verbose_name="Target Units",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduling Run",
                "verbose_name_plural": "Scheduling Runs",
                "ordering": ["-run_date"],
            },
        ),
        migrations.AddField(
            model_name="importbatch",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_batches",
                to="schedule.organization",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_batches",
                to="schedule.unit",
                verbose_name="Target Unit",
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CONSTRAINT", "Soldier Constraint"),
                            ("TRAINING", "Training"),
                            ("EXERCISE", "Military Exercise"),
                            ("HOLIDAY", "Holiday"),
                            ("MAINTENANCE", "Equipment Maintenance"),
                            ("INSPECTION", "Inspection"),
                            ("CEREMONY", "Ceremony"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Event Name")),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "min_required_soldiers",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Min Required Soldiers"
                    ),
                ),
                (
                    "base_days_per_soldier",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Base Days Per Soldier for Event",
                    ),
                ),
                (
                    "home_days_per_soldier",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Home Days Per Soldier for Event",
                    ),
                ),
                (
                    "max_home_days_per_soldier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Max Home Days Per Soldier"
                    ),
                ),
                (
                    "max_base_days_per_soldier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Max Base Days Per Soldier"
                    ),
                ),
                (
                    "max_consecutive_base_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Max Consecutive Base Days"
                    ),
                ),
                (
                    "max_consecutive_home_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Max Consecutive Home Days"
                    ),
                ),
                (
                    "min_consecutive_base_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Min Consecutive Base Days"
                    ),
                ),
                (
                    "min_consecutive_home_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Min Consecutive Home Days"
                    ),
                ),
                (
                    "min_base_block_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Min Base Block Days"
                    ),
                ),
                (
                    "max_base_block_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Max Base Block Days"
                    ),
                ),
                (
                    "max_weekend_base_days_per_soldier",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Max Weekend Base Days Per Soldier",
                    ),
                ),
                (
                    "require_weekend_coverage",
                    models.BooleanField(
                        default=True, verbose_name="Require Weekend Coverage"
                    ),
                ),
                (
                    "weekend_min_soldiers",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Min Soldiers Required on Weekends",
                    ),
                ),
                (
                    "force_rotation_days",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Force Rotation Every X Days",
                    ),
                ),
                (
                    "exceptional_soldier_distribution",
                    models.BooleanField(
                        default=True,
                        verbose_name="Distribute Exceptional Soldiers Evenly",
                    ),
                ),
                (
                    "balance_workload",
                    models.BooleanField(
                        default=True, verbose_name="Balance Workload Across Soldiers"
                    ),
                ),
                (
                    "workload_variance_tolerance",
                    models.FloatField(
                        blank=True,
                        default=0.1,
                        null=True,
                        verbose_name="Workload Variance Tolerance (0.0-1.0)",
                    ),
                ),
                (
                    "override_global_settings",
                    models.BooleanField(
                        default=False,
                        verbose_name="Override Global Scheduling Settings",
                    ),
                ),
                (
                    "priority_level",
                    models.IntegerField(default=5, verbose_name="Priority (1-10)"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, verbose_name="Mandatory Participation"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="schedule.organization",
                    ),
                ),
                (
                    "soldier_constraint",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_link",
                        to="schedule.soldierconstraint",
                    ),
                ),
                (
                    "specific_soldiers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="specific_events",
                        to="schedule.soldier",
                        verbose_name="Specific Soldiers",
                    ),
                ),
                (
                    "target_units",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events",
                        to="schedule.unit",
                        verbose_name="Target Units",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["start_date", "priority_level"],
            },
        ),
        migrations.CreateModel(
            name="UserOrganizationRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Organization Administrator"),
                            ("SCHEDULER", "Scheduler"),
                            ("UNIT_MANAGER", "Unit Manager"),
                            ("VIEWER", "View Only"),
                            ("SOLDIER", "Soldier (Self Service)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="schedule.organization",
                    ),
                ),
                (
                    "units",
                    models.ManyToManyField(
                        blank=True, to="schedule.unit", verbose_name="Managed Units"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Organization Role",
                "verbose_name_plural": "User Organization Roles",
                "unique_together": {("user", "organization")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="soldier",
            unique_together={("organization", "name")},
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_date", models.DateField(verbose_name="Assignment Date")),
                ("is_on_base", models.BooleanField(verbose_name="Is on Base?")),
                (
                    "shift_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Shift Type"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Assignment Location",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "scheduling_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="schedule.schedulingrun",
                    ),
                ),
                (
                    "soldier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.soldier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "ordering": ["assignment_date", "soldier__unit", "soldier__name"],
                "unique_together": {("scheduling_run", "soldier", "assignment_date")},
            },
        ),
    ]
