# Generated by Django 5.2.4 on 2025-07-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הרצה')),
                ('start_date', models.DateField(verbose_name='תאריך התחלה')),
                ('end_date', models.DateField(verbose_name='תאריך סיום')),
                ('default_base_days_target', models.IntegerField(verbose_name='יעד ימי בסיס ברירת מחדל')),
                ('default_home_days_target', models.IntegerField(verbose_name='יעד ימי בית ברירת מחדל')),
                ('max_consecutive_base_days', models.IntegerField(verbose_name='מקסימום ימי בסיס רצופים')),
                ('max_consecutive_home_days', models.IntegerField(verbose_name='מקסימום ימי בית רצופים')),
                ('min_base_block_days', models.IntegerField(verbose_name='מינימום ימים בבלוק בסיס')),
                ('min_required_soldiers_per_day', models.IntegerField(verbose_name='מינימום חיילים נדרשים ביום')),
                ('max_total_home_days', models.IntegerField(blank=True, null=True, verbose_name='מקסימום ימי בית כוללים')),
                ('status', models.CharField(choices=[('SUCCESS', 'הושלם בהצלחה'), ('FAILURE', 'נכשל'), ('IN_PROGRESS', 'בתהליך'), ('NO_SOLUTION', 'לא נמצא פתרון')], default='IN_PROGRESS', max_length=20, verbose_name='סטטוס הרצה')),
                ('solution_details', models.TextField(blank=True, null=True, verbose_name='פרטי פתרון/שגיאה')),
            ],
            options={
                'verbose_name': 'הרצת שיבוץ',
                'verbose_name_plural': 'הרצות שיבוץ',
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם חייל')),
            ],
            options={
                'verbose_name': 'חייל',
                'verbose_name_plural': 'חיילים',
            },
        ),
        migrations.CreateModel(
            name='SoldierConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_date', models.DateField(verbose_name='תאריך אילוץ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור אילוץ')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='schedule.soldier', verbose_name='חייל')),
            ],
            options={
                'verbose_name': 'אילוץ חייל',
                'verbose_name_plural': 'אילוצי חיילים',
                'ordering': ['constraint_date'],
                'unique_together': {('soldier', 'constraint_date')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CONSTRAINT', 'אילוץ חייל'), ('TRAINING', 'אימון'), ('HOLIDAY', 'חג'), ('OTHER', 'אחר')], default='OTHER', max_length=20, verbose_name='סוג אירוע')),
                ('name', models.CharField(max_length=200, verbose_name='שם אירוע')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
                ('start_date', models.DateField(verbose_name='תאריך התחלה')),
                ('end_date', models.DateField(verbose_name='תאריך סיום')),
                ('soldier_constraint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_link', to='schedule.soldierconstraint', verbose_name='אילוץ חייל מקושר')),
            ],
            options={
                'verbose_name': 'אירוע',
                'verbose_name_plural': 'אירועים',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(verbose_name='תאריך שיבוץ')),
                ('is_on_base', models.BooleanField(verbose_name='האם בבסיס?')),
                ('scheduling_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schedule.schedulingrun', verbose_name='הרצת שיבוץ')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.soldier', verbose_name='חייל')),
            ],
            options={
                'verbose_name': 'שיבוץ',
                'verbose_name_plural': 'שיבוצים',
                'ordering': ['assignment_date', 'soldier__name'],
                'unique_together': {('scheduling_run', 'soldier', 'assignment_date')},
            },
        ),
    ]
