# Generated by Django 4.2.23 on 2025-08-10 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldier',
            options={'ordering': ['event', 'rank', 'name'], 'verbose_name': 'Soldier', 'verbose_name_plural': 'Soldiers'},
        ),
        migrations.AddField(
            model_name='soldier',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldiers', to='schedule.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='soldier_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Soldier ID'),
        ),
        migrations.AlterUniqueTogether(
            name='soldier',
            unique_together={('event', 'soldier_id')},
        ),
    ]
