# Generated by Django 4.2.23 on 2025-07-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="balance_workload",
            field=models.BooleanField(
                default=True, verbose_name="Balance Workload Across Soldiers"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="exceptional_soldier_distribution",
            field=models.BooleanField(
                default=True, verbose_name="Distribute Exceptional Soldiers Evenly"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="force_rotation_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Force Rotation Every X Days"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="max_base_block_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Max Base Block Days"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="max_base_days_per_soldier",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Max Base Days Per Soldier"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="max_consecutive_base_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Max Consecutive Base Days"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="max_consecutive_home_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Max Consecutive Home Days"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="max_weekend_base_days_per_soldier",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Max Weekend Base Days Per Soldier"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="min_base_block_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Min Base Block Days"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="min_consecutive_base_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Min Consecutive Base Days"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="min_consecutive_home_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Min Consecutive Home Days"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="override_global_settings",
            field=models.BooleanField(
                default=False, verbose_name="Override Global Scheduling Settings"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="require_weekend_coverage",
            field=models.BooleanField(
                default=True, verbose_name="Require Weekend Coverage"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="weekend_min_soldiers",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Min Soldiers Required on Weekends"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="workload_variance_tolerance",
            field=models.FloatField(
                blank=True,
                default=0.1,
                null=True,
                verbose_name="Workload Variance Tolerance (0.0-1.0)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="base_days_per_soldier",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Base Days Per Soldier for Event"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="home_days_per_soldier",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Home Days Per Soldier for Event"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="max_home_days_per_soldier",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Max Home Days Per Soldier"
            ),
        ),
    ]
