# Generated by Django 5.2.4 on 2025-07-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='base_days_per_soldier',
            field=models.IntegerField(blank=True, help_text='יעד ימי בסיס לחייל במהלך אירוע זה.', null=True, verbose_name='ימי בסיס לחייל (באירוע זה)'),
        ),
        migrations.AddField(
            model_name='event',
            name='home_days_per_soldier',
            field=models.IntegerField(blank=True, help_text='יעד ימי בית לחייל במהלך אירוע זה.', null=True, verbose_name='ימי בית לחייל (באירוע זה)'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_home_days_per_soldier',
            field=models.IntegerField(blank=True, help_text='הגבלת ימי בית מקסימליים לחייל במהלך אירוע זה.', null=True, verbose_name='מקסימום ימי בית לחייל (באירוע זה)'),
        ),
        migrations.AddField(
            model_name='event',
            name='min_required_soldiers',
            field=models.IntegerField(blank=True, help_text='מספר מינימלי של חיילים הנדרשים לאירוע זה ביום.', null=True, verbose_name='מינימום חיילים נדרשים לאירוע'),
        ),
    ]
