# Generated by Django 4.2.23 on 2025-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_soldier_options_soldier_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_single_day_blocks',
            field=models.BooleanField(default=False, verbose_name='Allow Single Day Base Blocks'),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_adjust_for_constraints',
            field=models.BooleanField(default=True, verbose_name='Auto-Adjust for High Constraints'),
        ),
        migrations.AddField(
            model_name='event',
            name='constraint_safety_margin_percent',
            field=models.IntegerField(default=25, help_text='Extra home days percentage for exceptional soldiers', verbose_name='Constraint Safety Margin (%)'),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_home_balance_penalty',
            field=models.BooleanField(default=True, verbose_name='Enable Home Balance Penalty'),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_weekend_fairness_weight',
            field=models.BooleanField(default=True, verbose_name='Enable Weekend Fairness'),
        ),
        migrations.AddField(
            model_name='event',
            name='exceptional_constraint_threshold',
            field=models.IntegerField(default=10, help_text='Soldiers with more constraints than this are treated as exceptional', verbose_name='Exceptional Constraint Threshold'),
        ),
        migrations.AddField(
            model_name='event',
            name='home_balance_weight',
            field=models.FloatField(default=1.0, verbose_name='Home Balance Weight'),
        ),
        migrations.AddField(
            model_name='event',
            name='strict_consecutive_limits',
            field=models.BooleanField(default=True, verbose_name='Strict Consecutive Day Limits'),
        ),
        migrations.AddField(
            model_name='event',
            name='weekend_fairness_weight',
            field=models.FloatField(default=1.0, verbose_name='Weekend Fairness Weight'),
        ),
        migrations.AddField(
            model_name='event',
            name='weekend_only_max_base_days',
            field=models.IntegerField(default=14, help_text='Maximum consecutive base days for weekend-only soldiers', verbose_name='Weekend-Only Max Base Days'),
        ),
    ]
