# Generated by Django 5.2.4 on 2025-07-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_event_base_days_per_soldier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingrun',
            name='max_weekend_base_days_per_soldier',
            field=models.IntegerField(blank=True, null=True, verbose_name='מקסימום שבתות בבסיס לחייל'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='is_exceptional_output',
            field=models.BooleanField(default=False, verbose_name='חריג בכמות/רצף יציאות?'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='is_weekend_only_soldier_flag',
            field=models.BooleanField(default=False, verbose_name='חייל סופ"ש בלבד?'),
        ),
    ]
