# Generated by Django 4.2.23 on 2025-07-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_schedulingrun_max_weekend_base_days_per_soldier_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "ordering": ["assignment_date", "soldier__name"],
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["start_date"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterModelOptions(
            name="schedulingrun",
            options={
                "ordering": ["-run_date"],
                "verbose_name": "Scheduling Run",
                "verbose_name_plural": "Scheduling Runs",
            },
        ),
        migrations.AlterModelOptions(
            name="soldier",
            options={"verbose_name": "Soldier", "verbose_name_plural": "Soldiers"},
        ),
        migrations.AlterModelOptions(
            name="soldierconstraint",
            options={
                "ordering": ["constraint_date"],
                "verbose_name": "Soldier Constraint",
                "verbose_name_plural": "Soldier Constraints",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="soldiers",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                to="schedule.soldier",
                verbose_name="Associated Soldiers",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assignment_date",
            field=models.DateField(verbose_name="Assignment Date"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="is_on_base",
            field=models.BooleanField(verbose_name="Is on Base?"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="scheduling_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="schedule.schedulingrun",
                verbose_name="Scheduling Run",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="soldier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.soldier",
                verbose_name="Soldier",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="base_days_per_soldier",
            field=models.IntegerField(
                blank=True,
                help_text="Target base days per soldier during this event.",
                null=True,
                verbose_name="Base Days Per Soldier (for this event)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CONSTRAINT", "Soldier Constraint"),
                    ("TRAINING", "Training"),
                    ("HOLIDAY", "Holiday"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Event Type",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="home_days_per_soldier",
            field=models.IntegerField(
                blank=True,
                help_text="Target home days per soldier during this event.",
                null=True,
                verbose_name="Home Days Per Soldier (for this event)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="max_home_days_per_soldier",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum home days limit per soldier during this event.",
                null=True,
                verbose_name="Max Home Days Per Soldier (for this event)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="min_required_soldiers",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum number of soldiers required for this event per day.",
                null=True,
                verbose_name="Min Required Soldiers for Event",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Event Name"),
        ),
        migrations.AlterField(
            model_name="event",
            name="soldier_constraint",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_link",
                to="schedule.soldierconstraint",
                verbose_name="Linked Soldier Constraint",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="default_base_days_target",
            field=models.IntegerField(verbose_name="Default Base Days Target"),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="default_home_days_target",
            field=models.IntegerField(verbose_name="Default Home Days Target"),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="end_date",
            field=models.DateField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="max_consecutive_base_days",
            field=models.IntegerField(verbose_name="Max Consecutive Base Days"),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="max_consecutive_home_days",
            field=models.IntegerField(verbose_name="Max Consecutive Home Days"),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="max_total_home_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Max Total Home Days"
            ),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="max_weekend_base_days_per_soldier",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Max Weekend Base Days Per Soldier"
            ),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="min_base_block_days",
            field=models.IntegerField(verbose_name="Min Base Block Days"),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="min_required_soldiers_per_day",
            field=models.IntegerField(verbose_name="Min Required Soldiers Per Day"),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="run_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Run Date"),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="solution_details",
            field=models.TextField(
                blank=True, null=True, verbose_name="Solution/Error Details"
            ),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="schedulingrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Successfully Completed"),
                    ("FAILURE", "Failed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("NO_SOLUTION", "No Solution Found"),
                ],
                default="IN_PROGRESS",
                max_length=20,
                verbose_name="Run Status",
            ),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="is_exceptional_output",
            field=models.BooleanField(
                default=False, verbose_name="Exceptional Output/Sequence?"
            ),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="is_weekend_only_soldier_flag",
            field=models.BooleanField(
                default=False, verbose_name="Weekend Only Soldier?"
            ),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Soldier Name"
            ),
        ),
        migrations.AlterField(
            model_name="soldierconstraint",
            name="constraint_date",
            field=models.DateField(verbose_name="Constraint Date"),
        ),
        migrations.AlterField(
            model_name="soldierconstraint",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Constraint Description"
            ),
        ),
        migrations.AlterField(
            model_name="soldierconstraint",
            name="soldier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constraints",
                to="schedule.soldier",
                verbose_name="Soldier",
            ),
        ),
    ]
